FROM adoptopenjdk/openjdk11:alpine-slim@sha256:6cb09ce0cc198ab891a61ea9a02dfd6aefe2a640fcea6dec834ba0e9f2cae085 as stage1

MAINTAINER  Johannes Bühler <jonnybbb@gmail.com>

RUN apk add --no-cache bash