FROM adoptopenjdk/openjdk11:alpine-slim@sha256:54f589faa42018a5e07997cb8d4bbf59ec2c6c5b6fc6a88241fc558f717bac6c as stage1

MAINTAINER  Johannes Bühler <jonnybbb@gmail.com>

RUN apk add --no-cache bash